apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: admininfos.branch.dzht.com
spec:
  group: branch.dzht.com
  names:
    kind: AdminInfo
    listKind: AdminInfoList
    plural: admininfos
    singular: admininfo
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AdminInfo is the Schema for the admininfos API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AdminInfoSpec defines the desired state of AdminInfo
          type: object
        status:
          description: AdminInfoStatus defines the observed state of AdminInfo
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
