apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-sdk-pro1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operator-sdk-pro1
  template:
    metadata:
      labels:
        name: operator-sdk-pro1
    spec:
      serviceAccountName: operator-sdk-pro1
      containers:
        - name: operator-sdk-pro1
          # Replace this with the built image name
          image: wanghaihui/admin-operator:v0.0.1
          command:
          - operator_sdk_pro1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "operator-sdk-pro1"
